#!/bin/sh
set -e
if [ -z "$D" ]; then
	depmod -a 4.14.146-rt67-cg-8.5.0f0-xilinx-zynq-32
else
	# image.bbclass will call depmodwrapper after everything is installed,
	# no need to do it here as well
	:
fi

